### PR TITLE
fix(core): Avoid revisiting stages when traversing ancestors.

### PR DESCRIPTION
**Pull request by mtweten**
This change introduces a set to track visited nodes when traversing ancestors. Without this, it's possible to get into some bad scenarios depending on a pipeline's graph structure. 

Given a structure like this:
graph

The current ancestor code will end up traversing the same stages repeatedly and adding duplicate stages to the final ancestors list. As more "columns" are added to the graph, performance degrades further. 

In one of our pipelines with 6 columns of 10 stages each, we've seen the ancestors logic take nearly 30 minutes to complete when trying to view the pipeline in deck. Gate times out on the call to get pipeline executions due to hystrix timeouts, but the request continues in orca and ties up a thread for 30 minutes.

In this screenshot you can see an example execution of a pipeline with the same structure described above, in which I have the "column" stages not execute, and the single wait stages in between execute (all wait stages are set to wait for only 3 seconds). 

exampleexecution

You can see the further down the graph it gets, the longer each wait stage takes to actually execute and complete, taking far longer than the actual 3 seconds it's supposed to wait.

### CODE REVIEW

**Review by TrevinTeacutter — APPROVED** [review]

**Comment by TrevinTeacutter** [comment]
Are you gonna undo the other superpipeline change with this?

**Comment by mtweten** [comment]
@TrevinTeacutter Yeah, I've already reverted the 'hacks' we had in our builds.

**Review by jasonkshar — APPROVED** [review]
I approve this with the entirety of my body.

**Comment by robfletcher** [comment]
Sounds good. I apologize that my terrible ancestor traversal code performs to poorly. In my defense it was retrofitted to an existing structure.

**Comment by robfletcher** [comment]
Is the time spent because `ancestors` gets called multiple times, or is it a single call being so inefficient? I'm wondering if we can restructure the way relationships are stored, memoize the call, or something like that in order to make things more efficient in the first place.

**Comment by mtweten** [comment]
@robfletcher I've opened a PR to orca, so we can continue the conversation there - should get more input that way -> https://github.com/spinnaker/orca/pull/2349

**Pull request merged**
